// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9KnqViBKWEC-AuOBWdWDNgq5X2fVKuA',
    appId: '1:937803163248:web:45150224bf3df9acebf6b5',
    messagingSenderId: '937803163248',
    projectId: 'quicklap-39473',
    authDomain: 'quicklap-39473.firebaseapp.com',
    storageBucket: 'quicklap-39473.appspot.com',
    measurementId: 'G-3RS46LW3HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5xnFmX-xesNVEZN4WdVEhw1bGWUF81JQ',
    appId: '1:937803163248:android:587911fe03f72a98ebf6b5',
    messagingSenderId: '937803163248',
    projectId: 'quicklap-39473',
    storageBucket: 'quicklap-39473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Kumqh2ZT5gFff_BkgAHYPM6Sm6IEaw4',
    appId: '1:937803163248:ios:d04e9cb561a079eeebf6b5',
    messagingSenderId: '937803163248',
    projectId: 'quicklap-39473',
    storageBucket: 'quicklap-39473.appspot.com',
    iosClientId: '937803163248-74cfq3dlhh55ltgaii7ib05jrjfblkg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicklab.quicklab',
  );
}
